### Machine Learning

* Machine Learning is a method of teaching computers to learn from data and improve their performance automatically.


| Type                     | Description                          |
| ------------------------ | ------------------------------------ |
| Supervised Learning      | Learns from labeled data             |
| Unsupervised Learning    | Learns from unlabeled data           |
| Semi-Supervised Learning | Uses both labeled and unlabeled data |
| Reinforcement Learning   | Learns through rewards and penalties |



| Labeled Data                 | Unlabeled Data                   |
| ---------------------------- | -------------------------------- |
| Has correct answers (labels) | No correct answers               |
| Used in Supervised Learning  | Used in Unsupervised Learning    |
| Easier to train models       | Used to discover hidden patterns |
| Example: House Price Dataset | Example: Customer Purchase Data  |

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Data Science\Bike-Price-Prediciton\BIke prediction\csv\Cleaned_bike_data.csv')

In [7]:
df

      Unnamed: 0     price  kms_driven  owner  age  power  brand
0              0   35000.0     17654.0      1  3.0  110.0      1
1              1  119900.0     11000.0      1  4.0  350.0      2
2              2  600000.0       110.0      1  8.0  675.0      3
3              3   65000.0     16329.0      1  4.0  180.0      1
4              4   80000.0     10000.0      1  3.0  150.0      4
...          ...       ...         ...    ...  ...    ...    ...
7301        9362   25000.0     48587.0      1  8.0  150.0      6
7302        9369   35000.0     60000.0      1  9.0  220.0      7
7303        9370  450000.0      3430.0      1  4.0  750.0     15
7304        9371  139000.0     21300.0      1  4.0  400.0      7
7305        9372   80000.0      7127.0      1  5.0  220.0      7

[7306 rows x 7 columns]

| Aspect            | Classification                                                           | Regression                                                                  |
| ----------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| Output            | A category or class                                                      | A continuous numerical value                                                |
| Goal              | Assign data to predefined labels                                         | Predict a quantity                                                          |
| Example           | Spam vs. Not Spam                                                        | Predict house price                                                         |
| Target Variable   | Discrete                                                                 | Continuous                                                                  |
| Common Algorithms | Logistic Regression, Decision Trees, Random Forest, SVM, Neural Networks | Linear Regression, Decision Trees, Random Forest Regressor, Neural Networks |

In [8]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [9]:
x = df.drop('price',axis=1)

In [10]:
y = df[['price']]

In [11]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7301     48587.0      1  8.0  150.0      6
7302     60000.0      1  9.0  220.0      7
7303      3430.0      1  4.0  750.0     15
7304     21300.0      1  4.0  400.0      7
7305      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [12]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [13]:
#pip install scikit-learn

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((5844, 5), (5844, 1), (1462, 5), (1462, 1))

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()     #object creation
lr.fit(x_train,y_train)

LinearRegression()

LinearRegression()

**In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org**

In [17]:
bike_1 = lr.predict([[17654.0,	1,	3.0,	110.0,	1]])
bike_1

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[-9742.13864087]])

In [18]:
print(lr.score(x_train,y_train))
print(lr.score(x_test,y_test))

0.7116425245703818
0.7434808272417703

In [19]:
import joblib
joblib.dump(lr,'model.lb')

['model.lb']

In [20]:
model = joblib.load('model.lb')

In [21]:
model.predict([[10000.0	,1	,3.0,	150.0	,4]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[40743.51160974]])

In [22]:
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
dtr = DecisionTreeRegressor()

In [23]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [24]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [25]:
print(dtr.score(x_train,y_train))
print(dtr.score(x_test,y_test))

0.9978073030729452
0.8394687632993542

In [26]:
x_train

      kms_driven  owner  age  power  brand
6302     12061.0      1  4.0  180.0      1
7037     40000.0      2  7.0  220.0      7
640      28329.0      1  6.0  110.0      6
6153     10000.0      2  8.0  220.0      7
1755     26000.0      1  8.0  150.0      5
...          ...    ...  ...    ...    ...
5191     15383.0      1  2.0  100.0      7
5226     45263.0      1  6.0  150.0      8
5390     45000.0      1  6.0  100.0      6
860      14836.0      1  8.0  150.0      4
7270      2126.0      1  3.0  250.0      4

[5844 rows x 5 columns]

In [27]:
y_train

         price
6302   65000.0
7037   49000.0
640    32000.0
6153   36000.0
1755   70000.0
...        ...
5191   38000.0
5226   62000.0
5390   30000.0
860    40000.0
7270  115800.0

[5844 rows x 1 columns]

In [28]:
x_test

      kms_driven  owner   age  power  brand
7062     35000.0      1   9.0  250.0      5
4553      9066.0      1   5.0  250.0     14
6505     48000.0      1  17.0  100.0      6
1918     20222.0      1   5.0  150.0      7
5227     27167.0      1   5.0  150.0      8
...          ...    ...   ...    ...    ...
2045     98971.0      1   8.0  150.0      5
527       2881.0      1   7.0  250.0     14
1783      6517.0      1   2.0  350.0      2
5065      5222.0      1   5.0  350.0      2
565       2980.0      1   6.0  160.0      1

[1462 rows x 5 columns]

In [29]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [30]:
dtr.predict([[17654.0	,1	,3.0	,110.0	,1]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([38000.])

In [31]:
dtr.predict([[11000.0	,1,	4.0	,350.0	,2]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([129950.])

In [32]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor()
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [33]:
print(knr.score(x_train,y_train))
print(knr.score(x_test,y_test))

0.7959014087606904
0.6676682666067486

In [34]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [35]:
rfr.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [36]:
print(rfr.score(x_train,y_train))
print(rfr.score(x_test,y_test))

0.9861154569431818
0.8756595220803556

In [37]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [38]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7301     48587.0      1  8.0  150.0      6
7302     60000.0      1  9.0  220.0      7
7303      3430.0      1  4.0  750.0     15
7304     21300.0      1  4.0  400.0      7
7305      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [39]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((5844, 5), (5844, 1), (1462, 5), (1462, 1))

In [40]:
bnb = BernoulliNB()

In [41]:
bnb.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BernoulliNB()

In [42]:
bnb.score(x_train,y_train)

0.0242984257357974

In [43]:
bnb.score(x_test,y_test)

0.0280437756497948

In [44]:
pred = bnb.predict(x_test)

In [45]:
pred

array([35000., 35000., 35000., ..., 35000., 35000., 35000.], shape=(1462,))

In [46]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [47]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [48]:
gnb.score(x_train,y_train)

0.16478439425051336

In [49]:
gnb.score(x_test,y_test)

0.02051983584131327

In [50]:
mnb = MultinomialNB()
mnb.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MultinomialNB()

In [51]:
mnb.score(x_train,y_train)

0.054414784394250515

In [52]:
mnb.score(x_test,y_test)

0.02667578659370725